### ISSUE TITLE
unable to filter results from Get-AtaSuspiciousActivity 

### ISSUE THREAD

**Issue by BrogieB** [Microsoft/Advanced-Threat-Analytics#3] opened 2017-11-08 17:10 UTC
This works / returns results as expected
 Get-ATAMonitoringAlert | where-object {$_.status -like "*Open*"} | select Titlekey, id, severity

This returns no results:
Get-AtasuspiciousActivity | where-object {$_.status -like "*Open*" } | select TitleKey, id, severity

however
Get-AtasuspiciousActivity <with an appropriate ID> returns the data that should have came with the above open filter.

**Comment by Javanite** [comment] 2017-11-14 17:07
![image](https://user-images.githubusercontent.com/19479604/32793524-064e6816-c91b-11e7-8f1c-9c6a816c098b.png)

Hi BrogieB - If you see the attached image, I just copied and pasted your exact command into my lab and everything worked. Could you provide some extra detail on your PS Version, ATA Version, and current Module version? Screenshots would also help.

**Comment by BrogieB** [comment] 2017-11-14 17:29
Thanks Mike,
 I worked with Yoann @ Microsoft today, its an issue if your not running WMF 5.1, we were running powershell v4 on 2012r2 and it didn't handle the json stream formatting correctly. updating WMF to 5.1 resoled.

Regards,
 Steve

________________________________

**Comment by Javanite** [comment] 2017-11-14 17:31
~~Perfect, thanks! Closing this.~~

Edit: On second thought, you should not need v5.1 I ran my command successful on PS Version 4.0.

![image](https://user-images.githubusercontent.com/19479604/32794872-eb9f2704-c91e-11e7-94f7-3c854c98d13c.png)

**Comment by skwd** [comment] 2017-11-20 20:10
I got the same issue on powershell v4 on 2012r2.  The command Get-AtasuspiciousActivity return an unparsed json stream. 

![image](https://user-images.githubusercontent.com/3700099/33039088-e38bdf72-ce04-11e7-9731-84a3caa49988.png)

**Comment by Javanite** [comment] 2017-11-20 20:50
Hi skwd,

A couple questions if you wouldn't mind answering:

1. Could you confirm for me if you have any "Golden Ticket" suspicious activities? 
2. How many total SA's do you have in the console?

**Comment by skwd** [comment] 2017-11-20 21:00
Hi Javanite, 

1)  I currently don't have any "Golden Ticket" suspicious activites.
2) ALL(1178) = Open(3)+  Closed(630) + Suppressed(545) 

Thank you

**Comment by Javanite** [comment] 2017-11-20 21:02
Would you mind running the following commands in your current PS Session and let me know if it provides the same or different behavior?

$result = Invoke-RestMethod -Uri "https://$ATACenter/api/management/suspiciousActivities" -Method Get -UseDefaultCredentials
[System.Object]$result

**Comment by skwd** [comment] 2017-11-20 21:08
Yes i got the same result 
![image](https://user-images.githubusercontent.com/3700099/33041639-03676e8a-ce0d-11e7-8578-709744c4bdf8.png)

**Comment by Javanite** [comment] 2017-11-20 21:11
~~Thank you for validating. Would you please email me at mike.kassis@microsoft.com and we can coordinate a skype session to troubleshoot. I have some theories on the cause, but I won't be able to validate in my own lab.~~

**Edit**: I do believe I pinpointed the issue, and I think it is due to PowerShell v4 limitations on the JavaScriptSerializer class. I believe the fix is running the ATA Module from a server running WMF 5.1+, as the MaxJsonLength was increased to ~2GB. I was not able to verify this previously, but both instances of this issue pertained to ATA environments with large amounts of SA's. In addition, the problem went away once many of the SA's were deleted.

If I can come up with a clean way to increase the MaxJsonLength in WMF 4.0, I'll add it to the module, but that may take me a little time. 

I was hesitant to recommend WMF 5.1 as a requirement until I could verify a good reason, and I think we have it.

**Comment by skwd** [comment] 2017-11-21 13:13
Thank you Mike. After the installation of Win8.1AndW2K12R2-KB3191564-x64.msu. The server reboot. The command parsed correctly the json.

**Comment by Javanite** [comment] 2017-11-21 18:29
Thank you for the confirmation. I will continue to explore adding support for PowerShell v4 by increasing the parsing size, but it may be more trouble than it's worth. I apologize for the inconvenience, and I'm glad we sorted out the problem. Closing this issue.

**Closed as completed by Javanite** 2017-11-21 18:29 UTC
